name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:nWEL6OvCSEi4tH46M2R4hA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:fuBuy_4qQR6PjNkk9QjWDg/streams/AQAAACmO6jzINEmrlJNZojO1PhsAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:ss256v98Ts2d0AUqkU4QsQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:fuBuy_4qQR6PjNkk9QjWDg/streams/AQAAAFv34r48tkZtmDzvbMVdLMwAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Occupancy  
        run: |
          curl -X POST "https://:0ZAOKUjNQDCOCtnEc6AwmQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:fuBuy_4qQR6PjNkk9QjWDg/streams/AQAAAIOBpAqOWEzbnV_8WDKXx_oAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json 
