name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:vVtqTdoUQ5mYuhk9EOfQtA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:DwQHHp8zT36WfW6ITqLNeg/streams/AQAAAMQhOtfHY0s3pHCXTvgx8g4AAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:vVtqTdoUQ5mYuhk9EOfQtA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:DwQHHp8zT36WfW6ITqLNeg/streams/AQAAAMQhOtfHY0s3pHCXTvgx8g4AAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Occupancy  
        run: |
          curl -X POST "https://:vVtqTdoUQ5mYuhk9EOfQtA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:DwQHHp8zT36WfW6ITqLNeg/streams/AQAAAMQhOtfHY0s3pHCXTvgx8g4AAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json 
